### PR TITLE
Add GHC 7.10 support

### PR DESCRIPTION
**Pull request by taruti**
Hello

This adds GHC 7.10 support. Some of the dependencies (stable-maps) are not yet fixed, but have pending issues also.

### CODE REVIEW

**Comment by anton-k** [comment]
Hello, thanks for updates, but is it going to
work with previous versions if I apply the changes?

**Comment by FranklinChen** [comment]
It should. The changes are trivial, a result of the Applicative changes in the Prelude to GHC 7.10.

**Comment by anton-k** [comment]
It's not so simple. I rely on Boolean package. which is not going to compile with 7.10. I'm going to update the libs when 7.10 would become a part of Haskell Platform

**Comment by FranklinChen** [comment]
`Boolean` compiled fine under 7.10 for me. I just built `csound-expression` and made some sounds using my trivial fork of `stable-maps` and @taruti 's patch here. https://github.com/spell-music/csound-expression/pull/28

**Comment by anton-k** [comment]
With recent changes it works wit all GHCs from 7.8 to 8.4
going to be in the upcoming release.

**Pull request closed without merging**
